# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]




    #app.json:
            #class: AppBundle\Service\Json
            #arguments: ["@translator"]
    #client.client:
            #class: ClientBundle\Service\Client
            #arguments: ["@doctrine.orm.entity_manager", "@service_container", "@translator"]
    #client.validation:
            #class: ClientBundle\Service\Validation
            #arguments: ["@doctrine.orm.entity_manager", "@service_container"]

